#!/bin/bash

#SCALA_VERSION=2.13.14 ALMOND_VERSION=0.14.0-RC15
SCALA_VERSION=2.12.15 ALMOND_VERSION=0.13.1


# Install coursier
curl -Lo coursier https://git.io/coursier-cli
chmod +x coursier

# Install almond
./coursier bootstrap \
    -r jitpack \
    -i user -I user:sh.almond:scala-kernel-api_$SCALA_VERSION:$ALMOND_VERSION \
    sh.almond:scala-kernel_$SCALA_VERSION:$ALMOND_VERSION \
    --sources --default=true \
    -o almond
./almond --install --predef-code '
import $ivy.`edu.berkeley.cs::chisel3:3.5.3`
import $ivy.`edu.berkeley.cs::chiseltest:0.5.3`
import chisel3._
'

rm almond
rm coursier
